config/routes.rb
require 'sidekiq/web'

Gallery::Application.routes.draw do
  resources :apps

  devise_for :users

  # examples
  resources :example_photos

  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#hello'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
end

app/models/example_photo.rb
# class ExamplePhoto < ActiveRecord::Base
#   mount_uploader :photo, ExamplePhotoUploader
#   store_in_background :photo
#   # process_in_background :photo
# end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  def index
    @apps = App.all
  end

  # GET /apps/1
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  def create
    @app = App.new(app_params)

    if @app.save
      redirect_to @app, notice: 'App was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /apps/1
  def update
    if @app.update(app_params)
      redirect_to @app, notice: 'App was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /apps/1
  def destroy
    @app.destroy
    redirect_to apps_url, notice: 'App was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def app_params
      params.require(:app).permit(:name, :url, :image, :user_id)
    end
end

app/controllers/example_photos_controller.rb
class ExamplePhotosController < ApplicationController
  def create
    @example_photo = ExamplePhoto.new(photo_params)

    if @example_photo.save
      redirect_to :back
    else
      render :edit
    end
  end

  protected

  def photo_params
    params.require(:example_photo).permit(:photo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def hello
  end
end

app/helpers/apps_helper.rb
module AppsHelper
  def software_photo_url(software)
    software.url || gallery_fallback_photo
  end

  protected

  def gallery_fallback_photo
    image_path('home/submission_fallback_image.gif')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apps/_form.html.erb
<%= simple_form_for @app do |f| %>
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :image, as: :file %>

    <%= f.submit %>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Image</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.url %></td>
        <td><%= app.image %></td>
        <td><%= app.user %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<article id="app-details" class="content-section" itemscope itemtype="http://schema.org/SoftwareApplication">
  <div class="row">
    <aside class="large-4 push-8 columns" id="app-details-right">

      <figure class="app-image" itemprop="screenshot">
        <%= image_tag software_photo_url(@app), itemprop: 'image' %>
      </figure>

      <nav class="app-links">
        <ul class="no-bullet">
          <li><%= link_to "Visit Software", @app.url, class: "large button expand" %></li>
          <li itemprop="video" itemtype="http://schema.org/VideoObject">
            <%= link_to "Video Demonstration", "#", class: "large button expand app-links-video", itemprop: "url" %>
          </li>
        </ul>
      </nav>

    </aside>

    <div class="large-8 pull-4 columns" id="app-details-left">
      <h1 id="app-title" itemprop="name"><%= @app.name %></h1>
      <p>
        created by
        <%= link_to "stefano", '#', itemprop: 'author' %>
      </p>

      <hr>

      <p id="app-tagline" itemprop="tagline">
        The catchy one-liner that is a bit long and wraps on the next line. The catchy one-liner that is a bit long and wraps on the next line.
      </p>

      <hr>

      <ul class="no-bullet inline-list" id="app-labels">
        <li><span class="label stack">Ruby on Rails</span></li>
        <li><span class="label stack">Ruby</span></li>
        <li><span class="label stack">Ruby on Rails</span></li>
        <li><span class="label stack">Ruby</span></li>
        <li><span class="label stack">Haskel on Grails</span></li>
        <li><span class="label stack">Ruby on Rails</span></li>
        <li><span class="label stack">Ruby</span></li>
        <li><span class="label stack">Haskel on Grails</span></li>
        <li><span class="label stack">Ruby on Rails</span></li>
        <li><span class="label stack">Ruby</span></li>
        <li><span class="label stack">Haskel on Grails</span></li>
        <li><span class="label platform">Web</span></li>
        <li><span class="label platform">Holly</span></li>
      </ul>

      <div itemprop="description">
        <p>
          Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas faucibus mollis interdum.
        </p>

        <p>
          Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Vestibulum id ligula porta felis euismod semper. Cras mattis consectetur purus sit amet fermentum. Maecenas sed diam eget risus varius blandit sit amet non magna.
        </p>
      </div>
    </div>

  </div>
</article>

app/views/home/hello.html.erb
<%= link_to 'go check your apps', apps_path %>

app/views/layouts/_default_header.html.erb
<h1>Your site name</h1>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="row">
    <div class="large-12 columns" id="header-content">
      <% if content_for? :header %>
        <%= yield :header %>
      <% else %>
        <%= render 'layouts/default_header' %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_top_bar.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="#">Top Bar Title </a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li>
          <a href="#">Hello <%= current_user.email %></a>
        </li>
        <li>
          <%= link_to 'log out', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="has-form">
          <%= link_to 'Log in', new_user_session_path, class: 'button' %>
        </li>
        <li>
          <%= link_to 'or sign up', new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js" xmlns:fb="http://ogp.me/ns/fb#" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/"> <!--<![endif]-->
  <head prefix="og: http://ogp.me/ns#">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>App Gallery</title>

    <meta name="viewport" content="width=device-width">

    <%= csrf_meta_tags %>
    <%= yield :head %>

    <%= stylesheet_link_tag 'reimagine2' %>
    <%= stylesheet_link_tag 'application' %>

  </head>

  <%= content_tag :body, { id: "body-#{controller_name}", class: 'foundation-grid' } do %>
    <%= render "nav/global_nav/global_nav" %>

    <div id="container">
      <%= yield :header %>

      <div class="row">
        <div class="large-12 columns">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render 'reimagine2/challengepost/footer' %>
    <%= javascript_include_tag "application" %>
  <% end %>
</html>

app/views/nav/global_nav/_account_links.html.erb
<nav id="global-nav-find-and-post">
  <%= link_to "Find Challenges", root_url(ref: params[:ref] || "top-nav-find"), data: { role: "discover" }, id: 'global-nav-find-link' %>

  <%= link_to "Post Challenges", root_url(ref: params[:ref] || "top-nav-post"), data: { role: "post-challenge" }, id: 'global-nav-post-link' %>
</nav>

app/views/nav/global_nav/_drop_down_menus.html.erb
<ul class="drop-down-menu" id="global-nav-menu">
    <li id="global-nav-user" class="global-nav-menu-item" data-global-nav-user="base">
  <a class="drop-down" href="#" id="global-nav-screen-name">
  </a>

  <ul id="cpa-settings-list" class="dropped-down-list">
    <li>
      <a href="http://challengepost.com/users/katzmopolitan">
        Portfolio <em class="user-new-item">new</em>
</a>    </li>

      <li>
        <a href="http://manage.challengepost.com/dashboard">Manage challenges</a>
      </li>

    <li id="global-nav-user-settings">
      <a href="http://challengepost.com/settings">Settings</a>
    </li>

    <li id="global-nav-user-log-out" data-global-nav-user="log-out">
      <a href="http://secure.challengepost.com/users/logout">Log out</a>
    </li>

      <li id="global-nav-start-admin">
        <a href="https://secure.challengepost.com/modes/admin/enable" data-method="put" rel="nofollow">Start admin</a>
      </li>
  </ul>
</li>

</ul>

app/views/nav/global_nav/_global_nav.html.erb
<nav class="top-bar" id="global-nav">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to image_tag("http://challengepost0.assetspost.com/assets/shared/ChallengePost_logo-b1d8468b99e10af0c79d389beff042d8.png", alt: "ChallengePost"), root_url %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Find Challenges</a></li>
      <li><a href="#">Post Challenges</a></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#" id="global-nav-screen-name">Unknown</a>
        <ul class="dropdown">
          <li>
            <a href="#" class=""><em>new!</em> Portfolio</a>
          </li>
          <li>
            <a href="#" class="">Manage challenges</a>
          </li>
          <li>
            <a href="#" class="">Settings</a>
          </li>
          <li>
            <a href="#" class="">Log out</a>
          </li>

        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/nav/global_nav/_group_logo.html.erb
<div id="group-logo">
  <%= link_to image_tag("http://challengepost0.assetspost.com/assets/shared/ChallengePost_logo-b1d8468b99e10af0c79d389beff042d8.png", alt: "ChallengePost"), root_url %>
</div>